### ISSUE TITLE
error: could not compile

### ISSUE THREAD

**Issue by strawberry-code** [apoelstra/ots-viewer#1]
```
error[E0557]: feature has been removed
 --> /Users/me/.cargo/registry/src/github.com-1ecc6299db9ec823/state-0.2.2/src/lib.rs:1:12
  |
1 | #![feature(const_fn)]
  |            ^^^^^^^^ feature has been removed
  |
```

I run `cargo build` but I give the above error.

----
>  `rustc 1.62.0 (a8314ef7d 2022-06-27)` 
> `cargo 1.62.0 (a748cf5a3 2022-06-08)`

**Comment by apoelstra** [comment]
o.O sure, I'll go through this and modernize the codebase. But I'm a bit disappointed that compilation actually *broke*.

**Comment by strawberry-code** [comment]
I'm using ARM M1 processor, although I'm pretty sure it's not a problem... I'll put myself at your disposal if you have any questions

**Comment by apoelstra** [comment]
It's not the processor that's the issue ... the issue is that this crate uses a bunch of 2017-era web framework stuff that has broken out from under me.
