### ISSUE TITLE
Server cannot serve requests

### ISSUE THREAD

**Issue by strawberry-code** [apoelstra/ots-viewer#3]
After #1 now I am able to build without errors (but set rustc to nightly required).

Seems that the rocket server could be run successfully via `$ ./target/release/ots-viewer-server`, how ever it seems to be not able to serve something, I also tried ti put a minimal index.html somewhere around bot only 500 and 404 are returned.

The given screenshot should give a clearer idea about this. I never used rust before neither rocket. Maybe something fails while generating static website file from templates or maybe I miss something using rust.

<img width="1495" alt="Screenshot 2022-07-18 at 23 36 53" src="https://user-images.githubusercontent.com/18684103/179622428-ae4094f2-12c2-49da-8f04-6d398b6f34d0.png">

**Comment by apoelstra** [comment]
It looks like Rocket has changed in the two versions that I bumped it. It is giving me errors now "you must attach `Template::fairing()`.

**Comment by apoelstra** [comment]
> I never used rust before neither rocket.

I imagine you just want OTS to work, but if your goal is to learn Rust, this not-maintained-in-years crate is a bad place to start :)

**Comment by strawberry-code** [comment]
Nope :) my goal is not to learn Rust –I wish I had time to do it ... :)– but I am wandering around github looking for a repo that nicely prints the ots

I found this repo and I was curious, that's all
